version: '3.7'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
    networks: 
      - main_net
    

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 80:80
    volumes:
      - wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    networks: 
      - main_net
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: wordpress
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks: 
      - main_net
    
volumes:
  db_data:
  wp-app:

networks: 
  main_net:
